name: Deploy Api to Azure

on:
  [push]

env:
  AZURE_WEBAPP_NAME: APITest
  AZURE_WEBAPP_PACKAGE_PATH: '.' 
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: windows-latest   
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore NuGet packages
        run: dotnet restore APIWeb/APIWeb.sln

      - name: Build the project
        run: dotnet build APIWeb/APIWeb.sln --configuration Release

      - name: Run tests unitarios y guardar salida
        run: dotnet test APIWeb/APIWeb.sln --logger "console;verbosity=detailed" || true
        
      - name: Notificar en Slack (resultado de tests)
        uses: rtCamp/action-slack-notify@v2
        if: always()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_PIPELINERESULTS }}
          SLACK_TITLE: "🧪 Resultado de pipelines"
          SLACK_MESSAGE: |
            *🔍 Workflow:* `${{ github.workflow }}`
            *🌿 Rama:* `${{ github.ref_name }}`
            *👤 Autor:* `${{ github.actor }}`
            *📦 Commit:* <https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>
            *🔗 Run:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Ver ejecución>

      - name: Publish the project
        run: dotnet publish APIWeb/APIWeb.csproj -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp

